version: "3"
services:
  archiver:
    image: go-build
    container_name: "archiver"
    environment:
      - TZ=Asia/Tokyo
      - BINARY_NAMES=archiver
      - API_CERT=${API_CERT}
    volumes:
      - ./app/bin:/usr/bikeshare_api/app/bin
      - ./data:/usr/bikeshare_api/data
      - ./log:/usr/bikeshare_api/log
      - ./conf:/usr/bikeshare_api/conf
      - ./resource:/usr/bikeshare_api/resource
    extra_hosts: 
      - "hanetwi.ddns.net:192.168.10.153"
      - "dbserver:192.168.10.151"
    networks:
      pub-network:
        ipv4_address: 192.168.10.171

  stationfiller:
    image: go-build
    container_name: "stationfiller"
    environment:
      - TZ=Asia/Tokyo
      - BINARY_NAMES=stationfiller
      - API_CERT=${API_CERT}
    volumes:
      - ./app/bin:/usr/bikeshare_api/app/bin
      - ./data:/usr/bikeshare_api/data
      - ./log:/usr/bikeshare_api/log
      - ./conf:/usr/bikeshare_api/conf
      - ./resource:/usr/bikeshare_api/resource
    extra_hosts: 
      - "hanetwi.ddns.net:192.168.10.153"
      - "dbserver:192.168.10.151"
    networks:
      pub-network:
        ipv4_address: 192.168.10.172

  apiserver:
    image: go-build
    container_name: "apiserver"
    environment:
      - TZ=Asia/Tokyo
      - BINARY_NAMES=apiserver
      - API_CERT=${API_CERT}
    volumes:
      - ./app/bin:/usr/bikeshare_api/app/bin
      - ./data:/usr/bikeshare_api/data
      - ./log:/usr/bikeshare_api/log
      - ./conf:/usr/bikeshare_api/conf
      - ./resource:/usr/bikeshare_api/resource
    extra_hosts: 
      - "hanetwi.ddns.net:192.168.10.153"
      - "dbserver:192.168.10.151"
    ports:
      - "5001:5001"
    networks:
      pub-network:
        ipv4_address: 192.168.10.173

  grapher:
    image: go-build
    container_name: "grapher"
    environment:
      - TZ=Asia/Tokyo
      - BINARY_NAMES=grapher
      - API_CERT=${API_CERT}
    volumes:
      - ./app/bin:/usr/bikeshare_api/app/bin
      - ./data:/usr/bikeshare_api/data
      - ./log:/usr/bikeshare_api/log
      - ./conf:/usr/bikeshare_api/conf
      - ./resource:/usr/bikeshare_api/resource
    extra_hosts: 
      - "hanetwi.ddns.net:192.168.10.153"
      - "dbserver:192.168.10.151"
    ports:
      - "5010:5010"
    networks:
      pub-network:
        ipv4_address: 192.168.10.155

networks:
  pub-network:
    external: true