version: "3"
services:
  apiserver:
    image: go-build
    container_name: "apiserver"
    environment:
      - TZ=Asia/Tokyo
      - BINARY_NAMES=apiserver
      - API_CERT=${API_CERT}
    volumes:
      - ./app/bin:/usr/bikeshare_api/app/bin
      - ./data:/usr/bikeshare_api/data
      - ./log:/usr/bikeshare_api/log
      - ./conf:/usr/bikeshare_api/conf
      - ./resource:/usr/bikeshare_api/resource
    extra_hosts: 
      - "hanetwi.ddns.net:192.168.10.153"
      - "dbserver:192.168.10.151"
    ports:
      - "5001:5001"
    networks:
      pub-network:
        ipv4_address: 192.168.10.173

  grapher:
    image: go-build
    container_name: "grapher"
    environment:
      - TZ=Asia/Tokyo
      - BINARY_NAMES=grapher
      - API_CERT=${API_CERT}
    volumes:
      - ./app/bin:/usr/bikeshare_api/app/bin
      - ./data:/usr/bikeshare_api/data
      - ./log:/usr/bikeshare_api/log
      - ./conf:/usr/bikeshare_api/conf
      - ./resource:/usr/bikeshare_api/resource
    extra_hosts: 
      - "hanetwi.ddns.net:192.168.10.153"
      - "dbserver:192.168.10.151"
    ports:
      - "5010:5010"
    networks:
      pub-network:
        ipv4_address: 192.168.10.155

  maintenance:
    image: go-build
    container_name: "maintenance"
    environment:
      - TZ=Asia/Tokyo
      - BINARY_NAMES=notify
      - API_CERT=${API_CERT}
    volumes:
      - ./app/bin:/usr/bikeshare_api/app/bin
      - ./app/maintenance.sh:/usr/bikeshare_api/app/maintenance.sh
      - ./data:/usr/bikeshare_api/data
      - ./log:/usr/bikeshare_api/log
      - ./conf:/usr/bikeshare_api/conf
      - ./resource:/usr/bikeshare_api/resource
    extra_hosts: 
      - "hanetwi.ddns.net:192.168.10.153"
      - "dbserver:192.168.10.151"
    networks:
      pub-network:
        ipv4_address: 192.168.10.175
    command: sh /usr/bikeshare_api/app/maintenance.sh

  line:
    image: go-build
    container_name: "line"
    environment:
      - TZ=Asia/Tokyo
      - BINARY_NAMES=line
      - API_CERT=${API_CERT}
      - LINE_CLIENT_ID=${LINE_CLIENT_ID}
      - LINE_CLIENT_SECRET=${LINE_CLIENT_SECRET}
    volumes:
      - ./app/bin:/usr/bikeshare_api/app/bin
      - ./log:/usr/bikeshare_api/log
      - ./conf:/usr/bikeshare_api/conf
      - ./resource:/usr/bikeshare_api/resource
    extra_hosts: 
      - "hanetwi.ddns.net:192.168.10.153"
      - "dbserver:192.168.10.151"
    ports:
      - "5050:5050"
    networks:
      pub-network:
        ipv4_address: 192.168.10.154

networks:
  pub-network:
    external: true